import { BoardElement, TemplateDefinition } from '../types';

export const architectureTemplateElements: BoardElement[] = [
  // Frames (Tiers)
  {
    id: 'frame-client',
    type: 'frame',
    title: 'CLIENT & EDGE ACCESS LAYER',
    color: '#6366f1',
    x: 80,
    y: 80,
    width: 320,
    height: 600,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'frame-gateway',
    type: 'frame',
    title: 'API GATEWAY & SECURITY INGRESS',
    color: '#06b6d4',
    x: 460,
    y: 80,
    width: 300,
    height: 600,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'frame-services',
    type: 'frame',
    title: 'DISTRIBUTED MICROSERVICES TIER',
    color: '#8b5cf6',
    x: 820,
    y: 80,
    width: 360,
    height: 600,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'frame-data',
    type: 'frame',
    title: 'PERSISTENCE & EVENT STREAMING TIER',
    color: '#10b981',
    x: 1240,
    y: 80,
    width: 340,
    height: 600,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Client Nodes
  {
    id: 'node-web',
    type: 'rectangle',
    x: 110,
    y: 160,
    width: 260,
    height: 80,
    fill: '#1e1b4b',
    stroke: '#6366f1',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '🖥️ Web Client (React + Canvas)\nZero-install browser app',
    textColor: '#e0e7ff',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-mobile',
    type: 'rectangle',
    x: 110,
    y: 280,
    width: 260,
    height: 80,
    fill: '#1e1b4b',
    stroke: '#6366f1',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '📱 Mobile / Tablet Clients\nTouch & Apple Pencil gestures',
    textColor: '#e0e7ff',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-edge-cdn',
    type: 'cloud',
    x: 110,
    y: 420,
    width: 260,
    height: 120,
    fill: '#2e1065',
    stroke: '#a855f7',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '⚡ Global Anycast Edge CDN\nDDoS Mitigation & Asset Cache',
    textColor: '#f3e8ff',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Gateway Nodes
  {
    id: 'node-waf',
    type: 'diamond',
    x: 520,
    y: 150,
    width: 180,
    height: 120,
    fill: '#164e63',
    stroke: '#06b6d4',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '🛡️ WAF & TLS\nTermination',
    textColor: '#cffafe',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-api-gw',
    type: 'rectangle',
    x: 480,
    y: 330,
    width: 260,
    height: 90,
    fill: '#083344',
    stroke: '#0891b2',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '🔀 Envoy API Gateway\nRoute multiplexing & JWT validation',
    textColor: '#ecfeff',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-lb',
    type: 'hexagon',
    x: 520,
    y: 480,
    width: 180,
    height: 110,
    fill: '#155e75',
    stroke: '#22d3ee',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '⚖️ WebSocket\nLoad Balancer',
    textColor: '#ecfeff',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Microservices Nodes
  {
    id: 'node-ws-engine',
    type: 'rectangle',
    x: 850,
    y: 150,
    width: 300,
    height: 90,
    fill: '#2e1065',
    stroke: '#9333ea',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '⚡ Real-Time WS Engine (Cluster)\nSub-15ms delta broadcast & cursors',
    textColor: '#fae8ff',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-board-svc',
    type: 'rectangle',
    x: 850,
    y: 270,
    width: 300,
    height: 80,
    fill: '#3b0764',
    stroke: '#c084fc',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '📋 Board & Canvas State Service\nCRDT reconciler & history undo',
    textColor: '#f5d0fe',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-meeting-svc',
    type: 'rectangle',
    x: 850,
    y: 380,
    width: 300,
    height: 80,
    fill: '#312e81',
    stroke: '#818cf8',
    strokeWidth: 2,
    strokeStyle: 'solid',
    cornerRadius: 12,
    text: '🎙️ Meeting & Audio/Video SFU\nWebRTC mesh, presence & timers',
    textColor: '#e0e7ff',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-ai-svc',
    type: 'rectangle',
    x: 850,
    y: 490,
    width: 300,
    height: 80,
    fill: '#022c22',
    stroke: '#10b981',
    strokeWidth: 2,
    strokeStyle: 'dashed',
    cornerRadius: 12,
    text: '🤖 AI Strategy Co-Pilot\nDiagram synthesis & meeting summary',
    textColor: '#d1fae5',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Persistence Nodes
  {
    id: 'node-redis',
    type: 'cylinder',
    x: 1280,
    y: 150,
    width: 260,
    height: 100,
    fill: '#7f1d1d',
    stroke: '#ef4444',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '🚀 Redis Cluster (PubSub & Cache)\nEphemera, cursors, room channels',
    textColor: '#fee2e2',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-postgres',
    type: 'cylinder',
    x: 1280,
    y: 290,
    width: 260,
    height: 110,
    fill: '#064e3b',
    stroke: '#059669',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '🗄️ PostgreSQL Distributed\nMulti-region partitioned boards',
    textColor: '#ecfdf5',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'node-s3',
    type: 'cylinder',
    x: 1280,
    y: 440,
    width: 260,
    height: 100,
    fill: '#1e3a8a',
    stroke: '#3b82f6',
    strokeWidth: 2,
    strokeStyle: 'solid',
    text: '📦 S3 Cloud Object Store\nVector exports, board snapshots & media',
    textColor: '#dbeafe',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Connectors between layers
  {
    id: 'conn-web-gw',
    type: 'connector',
    startX: 370,
    startY: 200,
    endX: 480,
    endY: 360,
    style: 'curved',
    stroke: '#818cf8',
    strokeWidth: 2,
    strokeStyle: 'solid',
    startArrow: 'none',
    endArrow: 'arrow',
    label: 'WebSocket / WSS',
    zIndex: 3,
    createdBy: 'system',
    updatedAt: Date.now(),
    x: 370,
    y: 200,
    width: 110,
    height: 160,
  },
  {
    id: 'conn-gw-ws',
    type: 'connector',
    startX: 740,
    startY: 370,
    endX: 850,
    endY: 190,
    style: 'curved',
    stroke: '#22d3ee',
    strokeWidth: 2,
    strokeStyle: 'solid',
    startArrow: 'none',
    endArrow: 'arrow',
    label: 'Upstream WS',
    zIndex: 3,
    createdBy: 'system',
    updatedAt: Date.now(),
    x: 740,
    y: 190,
    width: 110,
    height: 180,
  },
  {
    id: 'conn-ws-redis',
    type: 'connector',
    startX: 1150,
    startY: 190,
    endX: 1280,
    endY: 190,
    style: 'straight',
    stroke: '#f87171',
    strokeWidth: 2,
    strokeStyle: 'solid',
    startArrow: 'none',
    endArrow: 'arrow',
    label: 'Sub-millisecond PubSub',
    zIndex: 3,
    createdBy: 'system',
    updatedAt: Date.now(),
    x: 1150,
    y: 190,
    width: 130,
    height: 20,
  },
  {
    id: 'conn-board-pg',
    type: 'connector',
    startX: 1150,
    startY: 310,
    endX: 1280,
    endY: 340,
    style: 'straight',
    stroke: '#34d399',
    strokeWidth: 2,
    strokeStyle: 'solid',
    startArrow: 'none',
    endArrow: 'arrow',
    label: 'Debounced JSON State Sync',
    zIndex: 3,
    createdBy: 'system',
    updatedAt: Date.now(),
    x: 1150,
    y: 310,
    width: 130,
    height: 30,
  },

  // Architecture Decisions & Sticky Notes
  {
    id: 'sticky-adr-1',
    type: 'sticky',
    x: 80,
    y: 710,
    width: 240,
    height: 160,
    color: '#fef08a',
    text: '📌 ADR-01: Low Latency Protocol\nDirect binary WebSocket streaming maintains end-to-end cursor latency under 16ms even with 50+ concurrent collaborators.',
    author: 'Elena Rostova (Lead Architect)',
    votes: ['user_elena', 'user_marcus'],
    angle: -1.5,
    zIndex: 4,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'sticky-adr-2',
    type: 'sticky',
    x: 460,
    y: 710,
    width: 250,
    height: 160,
    color: '#bae6fd',
    text: '💡 Resilience & Fault-Tolerance\nIf connection drops, client queues local actions and automatically reconciles via vector clocks when re-established.',
    author: 'Marcus Vance (Staff Eng)',
    votes: ['user_marcus'],
    angle: 1.2,
    zIndex: 4,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'sticky-adr-3',
    type: 'sticky',
    x: 820,
    y: 710,
    width: 260,
    height: 160,
    color: '#bbf7d0',
    text: '🎯 Canvas Performance Target\nRendering 2,000+ vector shapes smoothly at 60 FPS using hardware-accelerated SVG transforms with LOD culling.',
    author: 'Sarah Lin (Frontend Lead)',
    votes: ['user_sarah', 'user_elena', 'user_marcus'],
    angle: -0.8,
    zIndex: 4,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'sticky-adr-4',
    type: 'sticky',
    x: 1240,
    y: 710,
    width: 260,
    height: 160,
    color: '#fed7aa',
    text: '🔒 Enterprise Security Model\nEnd-to-end tenant isolation, SOC2 compliance, encrypted board exports, and audit logs for all strategic mapping.',
    author: 'David Kim (Head of Security)',
    votes: ['user_david'],
    angle: 2,
    zIndex: 4,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
];

export const swotTemplateElements: BoardElement[] = [
  // 4 Quadrants
  {
    id: 'swot-strengths-frame',
    type: 'frame',
    title: 'STRENGTHS (Internal Factors)',
    color: '#10b981',
    x: 100,
    y: 100,
    width: 500,
    height: 420,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'swot-weaknesses-frame',
    type: 'frame',
    title: 'WEAKNESSES (Internal Gaps)',
    color: '#f59e0b',
    x: 640,
    y: 100,
    width: 500,
    height: 420,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'swot-opportunities-frame',
    type: 'frame',
    title: 'OPPORTUNITIES (Market & Growth)',
    color: '#06b6d4',
    x: 100,
    y: 560,
    width: 500,
    height: 420,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'swot-threats-frame',
    type: 'frame',
    title: 'THREATS (External Risks)',
    color: '#f43f5e',
    x: 640,
    y: 560,
    width: 500,
    height: 420,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Strengths Stickies
  {
    id: 's-1',
    type: 'sticky',
    x: 130,
    y: 170,
    width: 200,
    height: 150,
    color: '#bbf7d0',
    text: '⚡ Instant Collaboration\nZero-lag real-time WebSockets with live cursor tracking creates instant engagement.',
    author: 'Elena',
    votes: ['user_1', 'user_2'],
    angle: -1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 's-2',
    type: 'sticky',
    x: 360,
    y: 170,
    width: 200,
    height: 150,
    color: '#bbf7d0',
    text: '🎨 Unified Suite\nMeeting audio/video simulation, timer, and voting all built into the canvas.',
    author: 'Marcus',
    votes: ['user_1', 'user_3'],
    angle: 1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 's-3',
    type: 'sticky',
    x: 240,
    y: 340,
    width: 210,
    height: 140,
    color: '#bbf7d0',
    text: '🔒 Enterprise-Ready\nHigh-density vector export & standalone board backups.',
    author: 'Sarah',
    votes: ['user_2'],
    angle: -2,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Weaknesses Stickies
  {
    id: 'w-1',
    type: 'sticky',
    x: 670,
    y: 170,
    width: 200,
    height: 150,
    color: '#fef08a',
    text: '🧩 Integrations\nNeed deeper two-way sync with Jira and GitHub issues.',
    author: 'Alex',
    votes: ['user_1', 'user_2', 'user_3'],
    angle: 1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'w-2',
    type: 'sticky',
    x: 900,
    y: 170,
    width: 200,
    height: 150,
    color: '#fef08a',
    text: '📱 Mobile Stylus\nNeed even deeper palm rejection optimization for iPads.',
    author: 'David',
    votes: ['user_3'],
    angle: -1.5,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Opportunities Stickies
  {
    id: 'o-1',
    type: 'sticky',
    x: 130,
    y: 630,
    width: 200,
    height: 150,
    color: '#bae6fd',
    text: '🤖 AI Strategy Synthesis\nOne-click turn sticky brainstorms into structured PRDs & user stories.',
    author: 'Elena',
    votes: ['user_1', 'user_2', 'user_4'],
    angle: 2,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'o-2',
    type: 'sticky',
    x: 360,
    y: 630,
    width: 200,
    height: 150,
    color: '#bae6fd',
    text: '🌐 Remote Engineering Teams\nIncreasing demand for visual architecture modeling tools.',
    author: 'Marcus',
    votes: ['user_2'],
    angle: -1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Threats Stickies
  {
    id: 't-1',
    type: 'sticky',
    x: 670,
    y: 630,
    width: 200,
    height: 150,
    color: '#fecdd3',
    text: '⚔️ Big Tech Incumbents\nMiro & FigJam expanding enterprise bundling.',
    author: 'Sarah',
    votes: ['user_1', 'user_4'],
    angle: -2,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 't-2',
    type: 'sticky',
    x: 900,
    y: 630,
    width: 200,
    height: 150,
    color: '#fecdd3',
    text: '⚡ Self-Hosted Demands\nGovernment & defense clients requiring on-prem air-gapped clusters.',
    author: 'David',
    votes: ['user_3'],
    angle: 1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
];

export const retrospectiveTemplateElements: BoardElement[] = [
  // 4 Retrospective Columns
  {
    id: 'retro-frame-1',
    type: 'frame',
    title: '🚀 WHAT WENT EXCEPTIONALLY WELL',
    color: '#10b981',
    x: 80,
    y: 100,
    width: 340,
    height: 680,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-frame-2',
    type: 'frame',
    title: '🔧 WHAT COULD BE IMPROVED',
    color: '#f59e0b',
    x: 460,
    y: 100,
    width: 340,
    height: 680,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-frame-3',
    type: 'frame',
    title: '❓ PUZZLES & QUESTIONS',
    color: '#8b5cf6',
    x: 840,
    y: 100,
    width: 340,
    height: 680,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-frame-4',
    type: 'frame',
    title: '🎯 COMMITTED ACTION ITEMS',
    color: '#06b6d4',
    x: 1220,
    y: 100,
    width: 360,
    height: 680,
    zIndex: 1,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Column 1 Stickies
  {
    id: 'retro-1-1',
    type: 'sticky',
    x: 110,
    y: 180,
    width: 280,
    height: 140,
    color: '#bbf7d0',
    text: '🎉 Shipped v2.4 ahead of schedule with 0 critical Sev-1 bugs during release week!',
    author: 'Elena',
    votes: ['user_1', 'user_2', 'user_3'],
    angle: -1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-1-2',
    type: 'sticky',
    x: 110,
    y: 340,
    width: 280,
    height: 140,
    color: '#bbf7d0',
    text: '🚀 The new canvas rendering pipeline reduced memory usage by 45% on large 1,000+ element boards.',
    author: 'Marcus',
    votes: ['user_2', 'user_4'],
    angle: 1,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Column 2 Stickies
  {
    id: 'retro-2-1',
    type: 'sticky',
    x: 490,
    y: 180,
    width: 280,
    height: 140,
    color: '#fef08a',
    text: '⚠️ CI/CD test suite flakiness caused delays on merge queues on Thursday afternoon.',
    author: 'Sarah',
    votes: ['user_1', 'user_4'],
    angle: -1.5,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-2-2',
    type: 'sticky',
    x: 490,
    y: 340,
    width: 280,
    height: 140,
    color: '#fef08a',
    text: '📋 Need clearer acceptance criteria on connector auto-routing stories before sprint grooming.',
    author: 'David',
    votes: ['user_3'],
    angle: 0.8,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Column 3 Stickies
  {
    id: 'retro-3-1',
    type: 'sticky',
    x: 870,
    y: 180,
    width: 280,
    height: 140,
    color: '#e9d5ff',
    text: '❓ Should we adopt WebGPU or stick to hardware-accelerated SVG/2D Canvas for upcoming shapes?',
    author: 'Marcus',
    votes: ['user_1', 'user_2'],
    angle: 1.2,
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },

  // Column 4 Strategy Action Cards
  {
    id: 'retro-action-1',
    type: 'strategyCard',
    x: 1250,
    y: 180,
    width: 300,
    height: 180,
    title: 'Migrate CI Test Pipeline to Docker Matrix',
    description: 'Isolate flaky end-to-end tests into parallel workers and add automated quarantine.',
    priority: 'high',
    status: 'in_progress',
    points: 5,
    assignee: 'Sarah Lin',
    tags: ['DevOps', 'CI/CD'],
    votes: ['user_1', 'user_3'],
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
  {
    id: 'retro-action-2',
    type: 'strategyCard',
    x: 1250,
    y: 380,
    width: 300,
    height: 180,
    title: 'Implement Magnetic Shape Connector Snapping',
    description: 'Anchor connector endpoints precisely to shape cardinal points (top, bottom, left, right).',
    priority: 'critical',
    status: 'review',
    points: 8,
    assignee: 'Marcus Chen',
    tags: ['Canvas', 'UX'],
    votes: ['user_2', 'user_4'],
    zIndex: 2,
    createdBy: 'system',
    updatedAt: Date.now(),
  },
];

export const allTemplates: TemplateDefinition[] = [
  {
    id: 'architecture',
    name: 'Cloud & System Architecture',
    category: 'architecture',
    description: 'High-availability distributed microservices, edge routing, real-time sync, and database clusters.',
    icon: 'Network',
    elements: architectureTemplateElements,
  },
  {
    id: 'swot',
    name: 'Product Strategy SWOT Matrix',
    category: 'strategy',
    description: 'Evaluate internal strengths, weaknesses, market opportunities, and competitive risks.',
    icon: 'Grid',
    elements: swotTemplateElements,
  },
  {
    id: 'retrospective',
    name: 'Agile Team Retrospective',
    category: 'agile',
    description: 'Multi-column collaborative sprint review with dot voting, sticky notes, and action cards.',
    icon: 'CheckSquare',
    elements: retrospectiveTemplateElements,
  },
];
